In [6]:
#import
from sklearn.model_selection import learning_curve, train_test_split,GridSearchCV
from sklearn import datasets
#from sklearnimport grid_search
import numpy as np

In [8]:
iris = datasets.load_iris()
print(iris.DESCR)
print(iris.target_names)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [11]:
X, y = iris.data, iris.target
print('Size of data : %s' % (X.shape, ))
print('Target value : %s' % np.unique(y))

Size of data : (150, 4)
Target value : [0 1 2]


In [13]:
print(X[0:10, :])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [15]:
sample = [[6, 4, 6, 2],]

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=1)
knn.fit(X, y)
predicted_value= knn.predict(sample)
print(iris.target_names[predicted_value])
print(knn.predict_proba(sample))

['virginica']
[[0. 0. 1.]]


In [20]:
knn= KNeighborsClassifier(n_neighbors=10, weights='distance')
knn.fit(X, y)
predicted_value= knn.predict(sample)
print(knn.predict_proba(sample))
print(iris.target_names[predicted_value])

[[0. 0. 1.]]
['virginica']


In [22]:
parameters = {'n_neighbors':(1, 3, 10), 'weights':('uniform', 'distance')}
knn_base= KNeighborsClassifier()
grid_search= GridSearchCV(knn_base, parameters)
grid_search.fit(X, y)
print(grid_search)
print(grid_search.best_params_)
#print(grid_search.grid_scores_)

GridSearchCV(cv=None, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_neighbors': (1, 3, 10), 'weights': ('uniform', 'distance')},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)
{'n_neighbors': 10, 'weights': 'distance'}
